const productList = [
  {
    id: 'product-1',
    image: require('../../assets/images/shoe-1.webp'),
    productName: 'Jordan 1 Retro High Tie Dye',
    rate: 4.5,
    numOfReviews: 40000,
    brandName: 'Adidas',
    price: 235,
    priceType: 'Dollar',
    isWatchlisted: true,
  },
  {
    id: 'product-2',
    image: require('../../assets/images/shoe-2.webp'),
    productName: 'Jordan 1 Retro High Tie Dye',
    rate: 2.2,
    numOfReviews: 12365,
    brandName: 'Adidas',
    price: 235.0,
    priceType: 'Dollar',
    isWatchlisted: true,
  },
  {
    id: 'product-3',
    image: require('../../assets/images/shoe-3.webp'),
    productName: 'Jordan 1 Retro High Tie Dye',
    rate: 1.5,
    numOfReviews: 13456,
    brandName: 'Adidas',
    price: 496.0,
    priceType: 'Dollar',
    isWatchlisted: true,
  },
  {
    id: 'product-4',
    image: require('../../assets/images/shoe-4.webp'),
    productName: 'Jordan 1 Retro High Tie Dye',
    rate: 1.5,
    numOfReviews: 13456,
    brandName: 'Adidas',
    price: 496.0,
    priceType: 'Dollar',
    isWatchlisted: true,
  },
  {
    id: 'product-5',
    image: require('../../assets/images/shoe-5.jpg'),
    productName: 'Jordan 1 Retro High Tie Dye',
    rate: 1.5,
    numOfReviews: 13456,
    brandName: 'Adidas',
    price: 496.0,
    priceType: 'Dollar',
    isWatchlisted: true,
  },
];

export default productList;
